### ISSUE TITLE
Adding a required field into request body is considered a compatible change

### ISSUE THREAD

**Issue by orange-buffalo** [OpenAPITools/openapi-diff#319]
Currently, when adding a new required field to the request body, the change is considered compatible - see https://github.com/orange-buffalo/openapi-diff/commit/e66b8670a2a34a636fa5d90ab1f3ddc09030adbf for the demonstration.

However, if API provider (a server) now requires a new field in the request, requests from existing API consumers (clients) will fail as they do not provide this field. Hence, the change is backwards incompatible.

**Comment by orange-buffalo** [comment]
It appeared to be our mistake - we defined required fields incorrectly:
```yaml
components:
  schemas:
    RequestDto:
      properties:
        addedField:
          type: string
          required: true
```
while OpenAPI schema required it to be defined as:
```yaml
components:
  schemas:
    RequestDto:
      required: ["addedField"]
      properties:
        addedField:
          type: string
```
After changing to proper definition the test passes. 

It would be great to validate the schemas before comparison (or at least use the strict YAML/JSON parsing rules), but that is a different story. 
Closing this issue.
