### ISSUE TITLE
If path parameter names are changed, parameter schema changes do not trigger incompatibility 

### ISSUE THREAD

**Issue by mishukdutta-toast** [OpenAPITools/openapi-diff#348]
### Old Schema
```
paths:
  /student/{id}:
    get:
      parameters:
        - in: path
          name: id   # Note the name is the same as in the path
          required: true
          schema:
            type: string
            pattern: A..Z a..z 0..9 . _ -
            minimum: 1
```

### Changed Schema
```
paths:
  /student/{username}:
    get:
      parameters:
        - in: path
          name: username   # Note the name is the same as in the path
          required: true
          schema:
            type: integer
            minimum: 1
```

The URI [`/student/{id}` & `/student/{username}` ] are (technically) same, 
**BUT** The parameters are different (`id` & `username`)

The `schema` differs (one takes in `string` & another `integer`)
Running`OpenApiCompare` does not detect any changes.

Keeping the URI parameters the same and changing the schema does trigger change detection.
