### ISSUE TITLE
allOf : `type` of property contained in multiple subschemas is not correctly determined.

### ISSUE THREAD

**Issue by thake** [OpenAPITools/openapi-diff#392]
Given the following schema V1:
```yaml
Foo:
  allOf:
    - properties:
        propA:
          type: string
    - properties:
        propA:
          example: "YEEHAA"
```

is changed to the following schema V2:
```yaml
Foo:  
  properties:
    propA:
      type: string
```

openapi-diff incorrectly detects the following incompatible change:
`Changed property type (object -> string)`

It seems to me that the `type` of a property that is contained in multiple subschemas of an allOf is not correctly determined. Openapi-diff recognized the type of `propA` in schema V1 as an object, but this is not correct.
