### ISSUE TITLE
Adding or removing 'uniqueItems' is not detected

### ISSUE THREAD

**Issue by michael-schnell** [OpenAPITools/openapi-diff#478]
Adding 'uniqueItems' like is currently not detected as a change:

**V1**
```
schema:
    type: array
    items:
        type: integer
```

**V2 (Added 'uniqueItems')**
```
schema:
    type: array
    items:
        type: integer
    uniqueItems: true
```

Same with removing 'uniqueItems':

**V1**
```
schema:
    type: array
    items:
        type: integer
    uniqueItems: true
```

**V2 (Removed'uniqueItems')**
```
schema:
    type: array
    items:
        type: integer
```

(Changing 'true' to 'false' or vice versa should be treated simply as adding/removing)
