### ISSUE TITLE
Changes on "minProperties" / "maxProperties" are not detected

### ISSUE THREAD

**Issue by michael-schnell** [OpenAPITools/openapi-diff#479]
Adding ,removing or changing "minProperties" and "maxProperies" is not detected.

**V1:**
```
schema:
    title: Foo
    type: object
    additionalProperties:
        title: Bar
        type: string
```
**V2 (Added 'maxProperties'):**
```
schema:
    title: Foo
    type: object
    maxProperties: 2
    additionalProperties:
        title: Bar
        type: string
```

Same with removing or changing the value.
