### ISSUE TITLE
Changes on 'minItems' and 'maxItems' not detected

### ISSUE THREAD

**Issue by michael-schnell** [OpenAPITools/openapi-diff#480]
Currently adding/removing/changing 'minItems' or 'maxItems' is not detected.

**V1**
```
schema:
    type: array
    items:
        type: integer
```
**V1 (Added 'maxItems')**
```
schema:
    type: array
    items:
        type: integer
    maxItems: 100
```

Same applies to 'minItems' or changing/removing the values.
