### ISSUE TITLE
Removal of 'deprecated' not detected

### ISSUE THREAD

**Issue by michael-schnell** [OpenAPITools/openapi-diff#485]
Removal of 'deprecated' is not detected iny any section (headers, operation,parameter, schema).

**V1**
```
headers:
    X-RateLimit-Limit:
      schema:
          type: integer
      deprecated: true
```
**V2 (removal of 'deprecated')**
```
headers:
    X-RateLimit-Limit:
      schema:
          type: integer
```

A new 'deprecated' is detected everywhere, but removal not.
