### ISSUE TITLE
Adding/Removing/Changing extensions is not detected

### ISSUE THREAD

**Issue by michael-schnell** [OpenAPITools/openapi-diff#487]
Adding below "x-bar", removing "x-foo" and changing the content of "x-extensible-enum" is not detected.

**V1**
```
application/json:
  schema:
    type: string
    x-extensible-enum: [one, two]
    x-foo: Foo
```
**V2**
```
application/json:
  schema:
    type: string
    x-extensible-enum: [one, two, three]
    x-bar: Bar
```
