### ISSUE TITLE
Output in text and markdown not equivalent (text output incomplete)

### ISSUE THREAD

**Issue by misko321** [OpenAPITools/openapi-diff#620]
The _text_ output which is printed by default by the CLI doesn't show all the information that the _markdown_ output shows:
#### spec1.yaml
```yaml
components:
  schemas:
    SomeDTO:
      someProperty:
        type: string
        enum:
          - ENUM_VALUE_1
          - ENUM_VALUE_2
```

#### spec2.yaml
```yaml
components:
  schemas:
    SomeDTO:
      someProperty:
        type: string
        enum:
          - ENUM_VALUE_1
          - ENUM_VALUE_2
          - ENUM_VALUE_3
```

---

#### _markdown_ output
```markdown
#### What's Changed
---

##### `GET` /resources1/{id}/resources2


###### Return Type:

Changed response : **200 OK**
> OK


* Changed content type : `application/json`

    Changed items (object):

    * Changed property `someProperty` (string)

        Added enum value:

        * `ENUM_VALUE_3`

```

#### _text_ output
```
==========================================================================
==                            API CHANGE LOG                            ==
==========================================================================
             API for Umetrics Core Project Management Service             
--------------------------------------------------------------------------
--                            What's Changed                            --
--------------------------------------------------------------------------
  Return Type:
    - Changed 200 OK
      Media types:
        - Changed application/json
          Schema: Broken compatibility
- GET    /resources1/{id}/resources2
                 API changes broke backward compatibility                 
--------------------------------------------------------------------------
```

**_text_ output tells nothing about what actually broke backwards compatibility, but since it's the stdout of the process it should show everything that's needed to determine the reason of the problem.**

Alternative solution: give an option to decide which kind of output: _text_/_markdown_/_json_ should be printed to stdout.
